Repository Quizeal/Backend, pull requests merged in 2021-08, with the labels that each got.

#14 Fixed major bugs
  Quizeal/settings.py
  Quizeal/urls.py
  core/migrations/0001_initial.py
  core/models.py
  core/urls.py
  core/views.py
  jwtapi/serializer.py
  jwtapi/views.py
Labels: bug

#16 feat: Added Load User Api
  Quizeal/settings.py
  Quizeal/urls.py
  jwtapi/serializer.py
  jwtapi/urls.py
  jwtapi/views.py
Labels: enhancement

#25 fix: Change Password and Delete
  core/migrations/0001_initial.py
  core/models.py
  core/urls.py
  core/views.py
Labels: enhancement, backend
